// Text-source font registry — the single source of truth for the Text
// generator's font list. Families must match the @font-face declarations in
// styles.css exactly (all bundled OFL/Apache, no CDN). ORDER MATTERS: a slot's
// `font` input stores an INDEX, so the original six stay first (saved sessions
// keep their face) and new families append after.
export const TEXT_FONTS = [
  // Original six — indices 0-5 are persisted in sessions/scenes.
  'Inter',
  'Space Grotesk',
  'JetBrains Mono',
  'Playfair Display',
  'Bebas Neue',
  'VT323',
  // Expansion (alphabetical).
  'Abril Fatface',
  'Alfa Slab One',
  'Anton',
  'Archivo Black',
  'Bangers',
  'Bungee',
  'Caveat',
  'Cinzel',
  'Comfortaa',
  'Cormorant',
  'Courier Prime',
  'Creepster',
  'Crimson Pro',
  'DM Sans',
  'DM Serif Display',
  'EB Garamond',
  'Fira Code',
  'Fraunces',
  'Josefin Sans',
  'Lexend',
  'Libre Baskerville',
  'Lobster',
  'Major Mono Display',
  'Manrope',
  'Monoton',
  'Orbitron',
  'Oswald',
  'Outfit',
  'Pacifico',
  'Permanent Marker',
  'Pixelify Sans',
  'Press Start 2P',
  'Raleway',
  'Righteous',
  'Rubik',
  'Rubik Mono One',
  'Shrikhand',
  'Silkscreen',
  'Special Elite',
  'Staatliches',
  'Syne',
  'Tektur',
  'Unbounded',
  'Zilla Slab'
]
