// Plain-English hover-help for shader inputs, keyed by shaderId → inputName.
// Surfaced by AutoControls in each control's title (appended to the label).
// Focused on the always-on finalizers (Vibe · Context · Finalizer) : the params
// a first-timer meets in Finishing and can't guess from the label alone.

export const INPUT_HINTS: Record<string, Record<string, string>> = {
  organic: {
    mode: 'Which element : fire (buoyant flames + sparks) · water (flowing caustics + deep) · nature (growing canopy + pollen).',
    rate: 'Overall speed of life : how fast the element moves / grows.',
    scale: 'Feature size : small = fine detail, large = broad masses.',
    detail: 'High-frequency texture on top of the base masses.',
    flow: 'Directional drift : the base current (flame rise · water flow · growth push).',
    swirl: 'Curl-noise turbulence : how much the flow eddies and billows (vs. smooth drift). The engine that makes it feel alive.',
    depth: 'Parallax depth : stacks a farther, dimmer layer behind (deep water · back-glow · far foliage) for volume.',
    embers: 'Drifting particle layer : rising sparks (fire) · sediment/bubbles (water) · pollen/leaves (nature). 0 = none.',
    vary: 'Season blend toward each element’s alternate : gas-blue flame · lagoon green · patchy autumn.',
    contrast: 'Tonal contrast of the element (harder vs. softer masses).'
  },
  'node-parallax': {
    amount: 'Parallax strength : how far near features shift relative to far ones. Needs the Depth engine on (header).',
    angle: 'Direction the parallax pushes.',
    sway: 'Animated camera drift — gives constant parallax motion even on a still image.',
    dof: 'Depth-of-field : blur that grows with distance from the focus plane.',
    focus: 'The depth that stays sharp (the focal plane).',
    fog: 'Aerial recession : the far distance sinks toward black.',
    invert: 'Flip near ↔ far.',
    wet: 'Dry/wet against the untouched image.'
  },
  'node-chronoscan': {
    source: 'What sets each pixel’s age into the frame history : SLIT-SCAN (a moving gradient — the scanner smear) · LUMA self (the image’s own brightness) · LUMA sidechain (another layer’s brightness as the clock).',
    reach: 'How far back the oldest regions read (up to ~32 frames of history).',
    angle: 'Direction of the slit-scan gradient (slit-scan control only).',
    sweep: 'Speed the slit-scan gradient drifts (a moving slit). 0 = static.',
    curve: 'Bends the time distribution : <1 crowds regions near the present, >1 near the past.',
    invert: 'Flip the age mapping (present ↔ past).',
    smooth: 'Cross-fade between the two nearest frames (smooth) vs. snap to one (stepped).',
    mix: 'Dry/wet against the live image.'
  },
  'node-sediment': {
    deposit: 'How strongly the present is laid down into the long memory.',
    decay: 'How slowly the memory fades : low = seconds, high = many minutes (the peaks sink back to black over this time).',
    resurface: 'How much of the old memory bleeds back under the live image.',
    age: 'Which past to resurface : 0 = the recent long-exposure accumulator, → 1 = the oldest kept keyframe (minutes ago).',
    interval: 'Seconds between keyframe snapshots. 16 slots × this = how far back the recallable past reaches.',
    stir: 'Slowly drifts the resurfaced memory so it sediments and wanders, rather than sitting as a frozen loop.',
    blend: 'How the memory combines with the live image : screen · lighten · under · difference.',
    mix: 'Dry/wet against the live image.'
  },
  'node-scanner': {
    mode: 'LOOP scans forever (continuous live slit-scan) · ONE-SHOT does a single pass on a trigger, then holds the frozen document.',
    axis: 'Which way the scan head sweeps : down / up / right / left.',
    scanRate: 'How fast the head sweeps (passes per second). Slow = long time-smear; fast = a quick refresh.',
    drag: 'Steady shear of the capture — the paper sliding under the head as it scans (diagonal smear).',
    wobble: 'A slow hand-wave across the sweep : wavy, organic distortion.',
    jitter: 'Random per-line horizontal rips (the digital tear).',
    tear: 'Chunkiness of the rips : low = per-line, high = torn in fat slabs.',
    rgb: 'CCD channel misregistration : splits R/G/B sideways (colour-fringe scanner artifact).',
    bar: 'Brightness of the moving scan bar (the bright line at the head). 0 hides it.',
    trig: 'FIRE a fresh scan pass on the rising edge. Press the button, send it over OSC, or bind a modulator (M) — a square LFO / sample&hold / audio edge — for rhythmic live re-scans.'
  },
  'node-autocutter': {
    cuts: 'How many pieces the frame is chopped into (recursive splits).',
    rotate: 'What fraction of the pieces get turned 90°/180°/270°.',
    slip: 'Nudges each piece’s source region — extra displacement / tearing.',
    gap: 'Dark seams drawn between the pieces (the collage cut lines).',
    mix: 'Blend of the rearranged cut-up against the untouched original.',
    rate: 'Auto re-cut rate (Hz) : >0 re-cuts on its own for hands-free live rhythm. 0 = only on trigger.',
    trig: 'Make a fresh cut on the rising edge. Press FIRE, send OSC, or bind a modulator (M) for rhythmic cutting.'
  },
  'fx-vibe': {
    stops: 'How many palette stops (2–5) the image is re-coloured toward : the size of the colour map.',
    blend: 'Blend of the palette re-colour against the original colours.',
    dither: 'Ordered dithering : breaks up banding, adds fine texture.',
    mixSrc: 'Mix the original source colours back in over the palette map.',
    autoLevel: 'Auto-levels : stretches contrast to use the full range.',
    gamma: 'Midtone brightness (below 1 darkens mids, above 1 lifts them).',
    contrast: 'Overall contrast.',
    saturation: 'Colour intensity (0 = greyscale).',
    sharpen: 'Edge sharpening.',
    splitTone: 'Split-tone amount : tints shadows and highlights toward two hues.',
    shadowTint: 'Colour pushed into the shadows (split-tone).',
    highTint: 'Colour pushed into the highlights (split-tone).',
    harmony: 'Nudges the palette hues toward a harmonic relationship.',
    baseHue: 'Base hue the generated palette is built around.',
    chroma: 'Palette colourfulness / saturation.',
    spread: 'Hue spread across the palette stops.',
    colorA: 'Palette stop A : a colour the image is mapped toward (darkest).',
    colorB: 'Palette stop B : a colour the image is mapped toward.',
    colorC: 'Palette stop C : a colour the image is mapped toward.',
    colorD: 'Palette stop D : a colour the image is mapped toward.',
    colorE: 'Palette stop E : a colour the image is mapped toward (lightest).'
  },
  'fx-context': {
    trails: 'Temporal colour bleed : past frames linger and drift into the distance.',
    blur: 'Soft spatial blur : takes the edge off, pushes things back in space.',
    bloom: 'Highlights glow / bleed light : dreamier, more luminous.',
    depth: 'Vignette + aerial recession that seats the image in a volume.',
    haze: 'Atmospheric veil toward the atmosphere colour : distance, air.',
    atmosphere: 'The colour the haze / aerial perspective tints toward.',
    lightGlow: "A soft key light's glow strength.",
    lightSize: 'Light spread : a tight spot (0) → a broad ambient wash (1).',
    lightColor: 'Colour of the key light.',
    light: 'Position of the key light (drag the XY pad).',
    pbrTexture: 'PBR material the whole composition is mapped onto (projector-on-surface look).',
    pbrAmount: 'RELIEF : how deep the material is — how far the image sinks into crevices and rides over bumps, and how much the surface relights it. 0 = flat passthrough.',
    pbrLight: 'RAKING : how hard the light grazes the material — independent of relief depth. Low = soft, even, front-lit. High = a low grazing light that throws long, near-black cast shadows in the crevices and hot specular sheen on the ridges (deep chiaroscuro contrast). Turn this up when the relief looks too flat.',
    pbrScale: 'Tiling scale of the PBR material : how many times it repeats across the frame.',
    pbrDepth: 'FIELD DEPTH : viewing distance. 0 = pressed against your eye (dense parallax, raking contrast). Up = you step back — the material tiles finer, the relief flattens, the light reads softer and more ambient, and the surface settles toward the atmosphere colour.',
    pbrNormal: 'PBR normal-map (relighting) strength.',
    pbrHeight: 'PBR displacement / height strength.',
    pbrAO: 'PBR ambient-occlusion (contact shadow) strength.'
  },
  'fx-finalizer': {
    black: 'Input black point : lifts or crushes the shadows (Levels).',
    white: 'Input white point : where the highlights clip (Levels).',
    gamma: 'Midtone brightness (Levels).',
    rGain: 'Red gain : tints the whole output.',
    gGain: 'Green gain : tints the whole output.',
    bGain: 'Blue gain : tints the whole output.',
    alpha: 'Output opacity.',
    sharpen: 'Final edge sharpening over the whole frame.',
    character: 'Grain character : digital sensor / film / CRT / VHS.',
    grain: 'Grain amount over the whole output.',
    grainSize: 'Grain particle size.',
    chroma: 'Colour noise in the grain.',
    parasites: 'CRT/VHS interference (head-switch tear, dropouts) : only with the crt/vhs character.',
    stereo: 'Render the output as red/cyan anaglyph 3D (needs red/cyan glasses). Gray = half-colour, gentler on the eyes for abstract relief.',
    stereoDepth: 'Strength of the 3D relief : how far the red/cyan eyes separate with depth.',
    stereoConv: 'Convergence : which depth sits ON the screen plane. Negative pushes forms OUT toward you (pop-out).',
    stereoInvert: 'Flip the depth reading (dark = near instead of bright = near).',
    filmHold: 'Cameraless / direct-film: hold the output on a hand-drawn draw clock. Film-hold = live process stepped; Freeze = a held cell that still weaves in the gate. (Distinct from the Transport Shutter, which is a global full-freeze stop-motion.)',
    filmRate: 'Draw frame rate : how many drawn frames per second (2–12 reads as hand-made film).',
    filmJitter: 'Irregularity of the draw-clock interval : hand timing is never metronomic.',
    filmBoil: 'Registration jitter : gate weave + hand-registration error (the "boil"), re-rolled per drawn frame.',
    filmFlutter: 'Per-frame density/luminance pump : uneven hand-painted exposure.',
    filmBlank: 'Chance a drawn frame shows blank leader instead of the picture (Blinkity-Blank intermittence).',
    filmBlankMode: 'Leader colour for blanks : black gap, white clear-leader flash, or both.',
    filmDust: 'Direct-on-film dirt & hair : sparse dark specks that sparkle frame to frame (+ rare bright emulsion pits).',
    filmScratch: 'Tramline scratches : near-vertical white lines that persist across several drawn frames.',
    filmGranule: 'Dye granulation / pooling : coarse clumped coloured mottle (the "paint" of hand-painted film).',
    filmSplice: 'Rare splice punctuation : a whole-frame flash + a bright horizontal bar.',
    outShape: 'Clip the finished frame into a silhouette (none = full frame).',
    outSize: 'Size of the output shape.',
    outAngle: 'Rotation of the output shape.',
    outPosX: 'Horizontal position of the output shape.',
    outPosY: 'Vertical position of the output shape.',
    outBgSource: "What fills OUTSIDE the shape : a solid colour or the Background layer (moved here).",
    outBgColor: "Fill colour outside the shape (when 'color' is chosen).",
    outDepth: 'Soft drop shadow : makes the shape float over the fill.',
    outShadowAngle: "Direction the shape's shadow falls (light angle).",
    outPerspective: 'Rakes the shadow onto a receding ground plane : adds depth realism.'
  }
}
