// Search keywords per shader id — the vocabulary a MUSICIAN would reach for.
// The FX / source pickers match the query against these as well as the name and
// family, so "reverb" surfaces Réponse, "bitcrush" surfaces Posterize / Decimate /
// Byte Corrupt, "delay" surfaces the echo family, "paint" surfaces Toile / Dye
// Field, "particles" surfaces Ash / Murmuration, and so on. Each entry is 4–6
// short tags blending the AUDIO metaphor (delay, reverb, compressor, bitcrush,
// wavefolder, filter, detune, tremolo, gate, granular…) with plain visual terms.
//
// Keep them lowercase; multi-word tags ("sample rate", "rgb split") are fine —
// the matcher does prefix / word / substring hits (see SearchSelect `score`).

export const SHADER_KEYWORDS: Record<string, string[]> = {
  // ── Native FX nodes ──────────────────────────────────────────────────
  'node-transfert': ['warp', 'optical flow', 'displace', 'sidechain', 'motion'],
  'node-convolve': ['convolution', 'kernel', 'bloom', 'stamp', 'impulse'],
  'node-mosaique': ['mosaic', 'mosaique', 'concatenative', 'tiles', 'photomosaic', 'patch', 'match', 'sidechain'],
  'node-reponse': ['delay', 'echo', 'reverb', 'trails', 'temporal'],
  'node-feedback': ['feedback', 'reverb', 'trails', 'tunnel', 'recursion'],
  'node-datamosh': ['datamosh', 'glitch', 'codec', 'smear', 'motion'],
  'node-scanner': ['slit scan', 'scan', 'smear', 'glitch', 'capture'],
  'node-autocutter': ['cut-up', 'collage', 'glitch', 'shuffle', 'mosaic'],
  'node-chronoscan': ['time warp', 'delay', 'slit scan', 'echo', 'temporal'],
  'node-sediment': ['long exposure', 'memory', 'reverb', 'delay', 'ghost'],
  'node-parallax': ['depth', 'parallax', '3d', 'blur', 'dof'],
  'node-eternalism': ['strobe', 'flicker', 'delay', 'persistence', 'echo'],
  'node-afterimage': ['afterimage', 'ghost', 'echo', 'complement', 'retinal'],
  'node-melt': ['melt', 'dissolve', 'liquid', 'drip', 'warp'],
  'node-faultline': ['glitch', 'dropout', 'cut', 'gate', 'stutter'],
  'node-ibfv': ['flow', 'feedback', 'smear', 'dye', 'wake'],
  'node-toile': ['paint', 'painterly', 'oil', 'ink', 'stylize'],
  'node-pulfrich': ['3d', 'stereo', 'depth', 'delay', 'anaglyph'],
  'node-corrode': ['corrode', 'decay', 'weather', 'rust', 'grunge'],
  'node-decimate': ['sample rate', 'decimate', 'stutter', 'hold', 'time-lapse'],

  // ── Rack FX ──────────────────────────────────────────────────────────
  'fx-abstraction': ['abstract', 'posterize', 'displace', 'simplify', 'reduce'],
  'fx-aperture': ['iris', 'vignette', 'gate', 'mask', 'lens'],
  'fx-byte-corrupt': ['bitcrush', 'glitch', 'corrupt', 'distortion', 'data'],
  'fx-chroma-shift': ['chromatic aberration', 'rgb split', 'detune', 'chorus', 'fringe'],
  'fx-colorizer': ['colorize', 'saturation', 'gradient', 'analog', 'tint', 'filter'],
  'fx-compress': ['compression', 'bitcrush', 'glitch', 'jpeg', 'blocks'],
  'fx-context': ['atmosphere', 'haze', 'depth', 'fog', 'vignette'],
  'fx-crt-screen': ['crt', 'retro', 'scanlines', 'vignette', 'monitor'],
  'fx-databend': ['databend', 'glitch', 'tear', 'stutter', 'data'],
  'fx-decay': ['vhs', 'tape', 'decay', 'glitch', 'lofi'],
  'fx-difference-bloom': ['motion', 'gate', 'difference', 'key', 'trails'],
  'fx-displace': ['displace', 'warp', 'wobble', 'lfo', 'distortion'],
  'fx-distort': ['distort', 'warp', 'ripple', 'swirl', 'bulge'],
  'fx-dither': ['dither', 'bitcrush', 'retro', 'texture', 'lofi'],
  'fx-edge': ['edge', 'outline', 'highpass', 'filter', 'contour', 'line'],
  'fx-feedback-zoom': ['feedback', 'zoom', 'echo', 'tunnel', 'trails'],
  'fx-finalizer': ['finalize', 'master', 'output', 'anaglyph', 'film'],
  'fx-fold': ['mirror', 'fold', 'kaleidoscope', 'reflect', 'symmetry'],
  'fx-force-lines': ['contour', 'lines', 'flow', 'etch', 'gradient'],
  'fx-grade': ['grade', 'contrast', 'compressor', 'eq', 'filter', 'levels'],
  'fx-grain': ['grain', 'noise', 'film', 'texture', 'hiss'],
  'fx-granular': ['granular', 'grains', 'shatter', 'scatter', 'texture'],
  'fx-hue-rotate': ['hue', 'color', 'rotate', 'shift', 'tint', 'filter'],
  'fx-light-trails': ['trails', 'delay', 'echo', 'long exposure', 'feedback'],
  'fx-mosaic': ['tiles', 'grid', 'mosaic', 'pixelate', 'blocks', 'downsample'],
  'fx-mosh-blocks': ['glitch', 'datamosh', 'blocks', 'bitcrush', 'corrupt'],
  'fx-motif': ['echo', 'counterpoint', 'delay', 'transpose', 'repeat'],
  'fx-ntsc': ['ntsc', 'vhs', 'retro', 'dot crawl', 'composite'],
  'fx-optical-rain': ['rain', 'streaks', '3d', 'anaglyph', 'stereo'],
  'fx-palette': ['palette', 'duotone', 'recolor', 'gradient', 'filter'],
  'fx-phosphene': ['afterimage', 'ghost', 'glow', 'retinal', 'echo'],
  'fx-pixelate': ['pixelate', 'bitcrush', 'mosaic', 'downsample', 'blocks'],
  'fx-pixelmask': ['mask', 'grille', 'stencil', 'halftone', 'pattern'],
  'fx-pixelsort': ['pixel sort', 'glitch', 'smear', 'sort', 'streak'],
  'fx-posterize': ['posterize', 'bitcrush', 'banding', 'quantize', 'flat'],
  'fx-rgb-shift': ['rgb split', 'chromatic aberration', 'detune', 'chorus', 'glitch'],
  'fx-ringing': ['ringing', 'echo', 'sharpen', 'ghost', 'artifact'],
  'fx-row-echo': ['echo', 'freeze', 'repeat', 'stutter', 'smear'],
  'fx-rutt': ['rutt etra', 'scan', 'displace', '3d', 'retro'],
  'fx-scanlines': ['scanlines', 'crt', 'retro', 'lines', 'monitor'],
  'fx-sharpen': ['sharpen', 'highpass', 'presence', 'crisp', 'detail'],
  'fx-slice-shuffle': ['glitch', 'slice', 'shuffle', 'stutter', 'cut'],
  'fx-slit-buffer': ['slit scan', 'freeze', 'smear', 'time', 'capture'],
  'fx-smear': ['smear', 'pixel sort', 'streak', 'drag', 'blur'],
  'fx-solarize': ['solarize', 'invert', 'distortion', 'contrast', 'psychedelic'],
  'fx-streak': ['streak', 'motion blur', 'drag', 'smear', 'blur'],
  'fx-stutter': ['stutter', 'freeze', 'glitch', 'hold', 'rhythm'],
  'fx-sync-loss': ['glitch', 'vhs', 'sync', 'roll', 'tear'],
  'fx-threshold': ['threshold', 'gate', 'key', 'contrast', 'silhouette'],
  'fx-tracking': ['vhs', 'tracking', 'glitch', 'retro', 'tape'],
  'fx-transform': ['transform', 'zoom', 'pan', 'rotate', 'crop'],
  'fx-triangle-flicker': ['strobe', 'flicker', 'tremolo', 'lfo', 'rhythm'],
  'fx-vibe': ['color grade', 'lut', 'look', 'film', 'palette'],
  'fx-wavefold': ['wavefolder', 'distortion', 'fold', 'saturation', 'drive'],
  'fx-wide-time': ['reverb', 'blur', 'delay', 'average', 'ghost'],

  // ── Generators / sources ─────────────────────────────────────────────
  ash: ['particles', 'ash', 'snow', 'embers', 'texture'],
  'column-scan': ['scan', 'lines', 'displace', 'waveform', 'oscillator'],
  congeal: ['feedback', 'flow', 'organic', 'warp', 'field'],
  contour: ['contour', 'topographic', 'lines', 'noise', 'matte'],
  differential: ['polyrhythm', 'oscillator', 'waves', 'harmonograph', 'geometry'],
  'direct-marks': ['film', 'scratches', 'marks', 'ink', 'hand-drawn'],
  'drift-field': ['flow', 'noise', 'bands', 'drift', 'matte'],
  'dye-field': ['paint', 'dye', 'ink', 'pigment', 'organic'],
  erosion: ['erosion', 'streaks', 'noise', 'geological', 'flow'],
  filaments: ['strands', 'kelp', 'lines', 'sway', 'organic'],
  'gen-collage': ['collage', 'video wall', 'cut-up', 'montage', 'grid'],
  'gen-parametric': ['audio', 'waveform', 'spectrum', 'oscilloscope', 'scope'],
  'gen-text': ['text', 'typography', 'words', 'title', 'font'],
  'grid-drift': ['grid', 'lines', 'geometry', 'drift', 'matrix'],
  interference: ['moiré', 'interference', 'beating', 'flanger', 'lines'],
  membrane: ['blob', 'organic', 'membrane', 'mass', 'breathing'],
  metamorph: ['morph', 'organic', 'blob', 'shapeshift', 'silhouette'],
  murmuration: ['flock', 'particles', 'swarm', 'birds', 'flow'],
  mycelium: ['network', 'branches', 'growth', 'organic', 'roots'],
  'op-art': ['op-art', 'optical', 'illusion', 'moiré', 'geometry'],
  organic: ['fire', 'water', 'organic', 'elemental', 'nature'],
  'particle-drift': ['particles', 'points', 'trails', 'flow', 'drift'],
  ramps: ['gradient', 'ramp', 'voltage', 'test', 'matte'],
  reaction: ['reaction-diffusion', 'organic', 'cells', 'pattern', 'spots'],
  recurse: ['recursion', 'fractal', 'kaleidoscope', 'geometry', 'droste'],
  'rgb-osc': ['oscillator', 'rgb', 'waveform', 'video synth', 'detune'],
  shapes: ['shapes', 'geometry', 'circle', 'primitive', 'matte'],
  slabs: ['glitch', 'slabs', 'bands', 'slice', 'matte'],
  'slit-scan': ['slit scan', 'time', 'oscillator', 'smear', 'scan'],
  'solid-color': ['color', 'fill', 'gradient', 'background', 'tint'],
  swell: ['water', 'waves', 'ocean', 'luminance', 'swell'],
  'sync-osc': ['oscillator', 'video synth', 'waveform', 'sync', 'sawtooth'],
  'ten-print': ['maze', '10print', 'retro', 'pattern', 'commodore']
}

/** Keywords for a shader id (empty when none authored). */
export function keywordsFor(id: string | undefined): string[] | undefined {
  return id ? SHADER_KEYWORDS[id] : undefined
}
